const ERROR_INACCURATE_DATA = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_INTERNAL_SERVER = 500;
const ERROR_UNAUTHORIZED = 401;
const ERROR_CONFLICT = 409;

module.exports = {
  ERROR_INACCURATE_DATA,
  ERROR_NOT_FOUND,
  ERROR_INTERNAL_SERVER,
  ERROR_UNAUTHORIZED,
  ERROR_CONFLICT,
};
